let nifty50 = [
  "INDUSINDBK",
  "BAJFINANCE",
  "TATACONSUM",
  "UPL",
  "LT",
  "BAJAJFINSV",
  "ASIANPAINT",
  "BPCL",
  "HINDALCO",
  "TECHM",
  "POWERGRID",
  "GRASIM",
  "BAJAJ-AUTO",
  "AXISBANK",
  "ADANIPORTS",
  "EICHERMOT",
  "DIVISLAB",
  "NESTLEIND",
  "INFY",
  "SHREECEM",
  "BHARTIARTL",
  "M&M",
  "HDFCLIFE",
  "TATASTEEL",
  "MARUTI",
  "APOLLOHOSP",
  "TITAN",
  "HCLTECH",
  "ULTRACEMCO",
  "HEROMOTOCO",
  "HDFC",
  "ONGC",
  "SBIN",
  "TCS",
  "ITC",
  "SUNPHARMA",
  "BRITANNIA",
  "COALINDIA",
  "WIPRO",
  "ICICIBANK",
  "TATAMOTORS",
  "HINDUNILVR",
  "NTPC",
  "HDFCBANK",
  "JSWSTEEL",
  "RELIANCE",
  "CIPLA",
  "KOTAKBANK",
  "SBILIFE",
  "DRREDDY",
];

let disp = (item) => console.log(item);

nifty50.slice(1,10).forEach(item => disp(item))

console.log('reverse');

nifty50.slice(-10,-10).forEach(item=>disp(item))