let dataObjs = [
  {
    filePath:
      "data/dataflow/testdata/srg/21.c/21.c_sort/src-os-csv-sort-multiple-targets-os-csv-write-to-single-file-false-override.yml",
    error:
      "java.lang.AssertionError: Getting file entity failed wtsf_it/overwrite_wtsf_false_1/ expected [200] but found [500]",
    errorDetail: [
      "java.lang.AssertionError: Getting file entity failed wtsf_it/overwrite_wtsf_false_1/ expected [200] but found [500]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.utility.NodeUtility.getFileEntity(NodeUtility.java:497)",
      "\tat com.oracle.dis.rest.dataflow.nodes.TargetBuilderNode.buildNode(TargetBuilderNode.java:107)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.recurse(PipelineUtility.java:46)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.recurse(PipelineUtility.java:57)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.recurse(PipelineUtility.java:57)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.recurse(PipelineUtility.java:57)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.buildPipeline(PipelineUtility.java:29)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.getPipeline(PipelineUtility.java:69)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.createDataFlowDetailsRequestPayload(PipelineUtility.java:96)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createDataFlow(DataFlowBaseTest.java:1771)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createIntegrationTask(DataFlowBaseTest.java:1740)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1781)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.c/21.c_sort/src-os-csv-sort-multiple-targets-os-csv-write-to-single-file-true-override.yml",
    error:
      "java.lang.AssertionError: Getting file entity failed wtsf_it/bank_customer_target_1wtsf_it/overwrite_bank_customer_target_2.csv expected [200] but found [404]",
    errorDetail: [
      "java.lang.AssertionError: Getting file entity failed wtsf_it/bank_customer_target_1wtsf_it/overwrite_bank_customer_target_2.csv expected [200] but found [404]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.utility.NodeUtility.getFileEntity(NodeUtility.java:497)",
      "\tat com.oracle.dis.rest.dataflow.nodes.TargetBuilderNode.buildNode(TargetBuilderNode.java:107)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.recurse(PipelineUtility.java:46)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.recurse(PipelineUtility.java:57)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.recurse(PipelineUtility.java:57)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.recurse(PipelineUtility.java:57)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.buildPipeline(PipelineUtility.java:29)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.getPipeline(PipelineUtility.java:69)",
      "\tat com.oracle.dis.rest.dataflow.utility.PipelineUtility.createDataFlowDetailsRequestPayload(PipelineUtility.java:96)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createDataFlow(DataFlowBaseTest.java:1771)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createIntegrationTask(DataFlowBaseTest.java:1740)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1781)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_hierarchy/Infer_Expression_Type/src-os-json-expr-inferType-tgt-os-json-struct-array-hierarchy-rev-eng.yml",
    error:
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [0]",
    errorDetail: [
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [0]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileCount(TargetFileValidator.java:97)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:703)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_hierarchy/Infer_Expression_Type/src-os-json-expr-inferType-tgt-os-json-struct-array-hierarchy-fwd-eng.yml",
    error:
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [0]",
    errorDetail: [
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [0]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileCount(TargetFileValidator.java:97)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:703)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_hierarchy/src-os-parquet-tgt-os-parquet-map-map-hierarchy-new.yml",
    error: "java.lang.AssertionError: Test failed while listing test data.",
    errorDetail: [
      "java.lang.AssertionError: Test failed while listing test data.",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat com.oracle.dis.rest.test.sdk.TestDataUtility.getFiles(TestDataUtility.java:66)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.ParquetFileValidator.validateFileContent(ParquetFileValidator.java:55)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:709)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_hierarchy/src-os-json-union-by-position-tgt-os-json-array-hierarchy-new.yml",
    error:
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [500]",
    errorDetail: [
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [500]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileCount(TargetFileValidator.java:97)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:703)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_hierarchy/src-os-avro-minus-by-name-tgt-os-json-array-hierarchy-new.yml",
    error:
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [250]",
    errorDetail: [
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [250]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileCount(TargetFileValidator.java:97)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:703)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_hierarchy/src-os-avro-union-by-name-tgt-os-json-array-hierarchy-new.yml",
    error:
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [502]",
    errorDetail: [
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [502]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileCount(TargetFileValidator.java:97)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:703)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_hierarchy/src-os-avro-intersect-by-name-tgt-os-json-array-hierarchy-new.yml",
    error:
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [503]",
    errorDetail: [
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [503]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileCount(TargetFileValidator.java:97)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:703)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_hierarchy/src-os-json-minus-by-position-tgt-os-json-array-hierarchy-new.yml",
    error:
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [251]",
    errorDetail: [
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [251]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileCount(TargetFileValidator.java:97)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:703)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_hierarchy/src-os-avro-tgt-os-parquet-map-map-hierarchy-new.yml",
    error: "java.lang.AssertionError: Test failed while listing test data.",
    errorDetail: [
      "java.lang.AssertionError: Test failed while listing test data.",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat com.oracle.dis.rest.test.sdk.TestDataUtility.getFiles(TestDataUtility.java:66)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.ParquetFileValidator.validateFileContent(ParquetFileValidator.java:55)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:709)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_hierarchy/src-os-json-intersect-by-position-tgt-os-json-array-hierarchy-new.yml",
    error:
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [505]",
    errorDetail: [
      "java.lang.AssertionError: No of files expected target and actual target files are not matching expected [1] but found [505]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileCount(TargetFileValidator.java:97)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:703)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_function/src-os-json-auto-fnOpJson-echoFields-hierarchy-tgt-json.yml",
    error:
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
    errorDetail: [
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileContent(TargetFileValidator.java:172)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:709)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_function/src-os-avro-dfm-fnOpJson-map-hierarchy-parquet-tgt.yml",
    error:
      "java.lang.AssertionError: No of records are not equal expected [2] but found [4]",
    errorDetail: [
      "java.lang.AssertionError: No of records are not equal expected [2] but found [4]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.ParquetFileValidator.validateRowCount(ParquetFileValidator.java:61)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.ParquetFileValidator.validateFileContent(ParquetFileValidator.java:33)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.ParquetFileValidator.validateFileContent(ParquetFileValidator.java:56)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:709)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d/21.d_function/src-os-json-auto-fnOpJson-structofstructofarrayofstruct-hierarchy-json-tgt.yml",
    error:
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
    errorDetail: [
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileContent(TargetFileValidator.java:172)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:709)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/21.d.4_target_load_order/src-db-multiple-tgt-db-multiple-target-load-order.yml",
    error:
      "java.lang.AssertionError: Task run DF_SRC_TGT_LOAD_TARGET_LOAD_ORDER_8E4DF7B9_286F_460E_9355_1C31932E5CB9_TUQI4_1661164581374_22898881: Work flow run status is not as expected. expected [SUCCESS] but found [ERROR]",
    errorDetail: [
      "java.lang.AssertionError: Task run DF_SRC_TGT_LOAD_TARGET_LOAD_ORDER_8E4DF7B9_286F_460E_9355_1C31932E5CB9_TUQI4_1661164581374_22898881: Work flow run status is not as expected. expected [SUCCESS] but found [ERROR]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:629)",
      "\tat com.oracle.dis.rest.validation.WorkflowServiceValidator.waitAndValidateResponse(WorkflowServiceValidator.java:93)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateMultiTargets$26(DataFlowBaseTest.java:2499)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateMultiTargets(DataFlowBaseTest.java:2483)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2456)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/22.a_function/src-os-json-auto-fnOpJsonBytes-echoFields-hierarchy-tgt-json.yml",
    error:
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
    errorDetail: [
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileContent(TargetFileValidator.java:172)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:709)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/22.a_function/src-os-json-auto-fnOpJsonBytes-structofstructofarrayofstruct-hierarchy-json-tgt.yml",
    error:
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
    errorDetail: [
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileContent(TargetFileValidator.java:172)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:709)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/22.a_function/src-os-avro-dfm-fnOpJsonBytes-map-hierarchy-parquet-tgt.yml",
    error:
      "java.lang.AssertionError: No of records are not equal expected [2] but found [4]",
    errorDetail: [
      "java.lang.AssertionError: No of records are not equal expected [2] but found [4]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat org.testng.Assert.assertEquals(Assert.java:907)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.ParquetFileValidator.validateRowCount(ParquetFileValidator.java:61)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.ParquetFileValidator.validateFileContent(ParquetFileValidator.java:33)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.ParquetFileValidator.validateFileContent(ParquetFileValidator.java:56)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:709)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/22.a_function/src-os-json-auto-fnOpJsonBytes-array-hierarchy-json-tgt.yml",
    error:
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
    errorDetail: [
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileContent(TargetFileValidator.java:172)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:709)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
  {
    filePath:
      "data/dataflow/testdata/srg/22.a_function/src-os-json-auto-fnOpJsonBytes-jagged-hierarchy-tgt-json.yml",
    error:
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
    errorDetail: [
      "java.lang.AssertionError: File Content Comparison failed expected [true] but found [false]",
      "\tat org.testng.Assert.fail(Assert.java:99)",
      "\tat org.testng.Assert.failNotEquals(Assert.java:1037)",
      "\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)",
      "\tat org.testng.Assert.assertEquals(Assert.java:122)",
      "\tat com.oracle.dis.rest.dataflow.sdk.common.validator.file.TargetFileValidator.validateFileContent(TargetFileValidator.java:172)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateTargetData(DataFlowBaseTest.java:709)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.lambda$validateData$1(DataFlowBaseTest.java:622)",
      "\tat java.util.ArrayList.forEach(ArrayList.java:1259)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateData(DataFlowBaseTest.java:620)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validatedTaskAndData(DataFlowBaseTest.java:2473)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.validateExecution(DataFlowBaseTest.java:2453)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowBaseTest.createAndExecuteIntegrationTask(DataFlowBaseTest.java:1802)",
      "\tat com.oracle.dis.rest.test.dataflow.DataFlowServiceE2ETest.testDataFlow(DataFlowServiceE2ETest.java:370)",
      "\tat sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)",
      "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "\tat java.lang.reflect.Method.invoke(Method.java:498)",
      "\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)",
      "\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)",
      "\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)",
      "\tat org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)",
      "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)",
      "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)",
      "\tat java.lang.Thread.run(Thread.java:750)",
      "",
    ],
  },
];

module.exports = {
    dataObjs
}